### ISSUE TITLE
I can't find the jar file

### ISSUE THREAD

**Issue by denispionicul** [Tharthar2/SaF2021#2]
I can't find the root/build/libs folders nor the jar file. I need a bit of helping getting the jar file

**Comment by Pugnatir** [comment]
same problem

**Comment by minhtet-htoon** [comment]
Sorry for the poor wording. By root, I mean the directory in which the gradle build file is stored, not the system root. If the build file was at c:\Users\me\documents\SaF2021\build.gradle, the root would be c:\Users\me\documents\SaF2021. The jar would the be at c:\Users\me\documents\SaF2021\build\libs

**Comment by denispionicul** [comment]
For some reason i don't have those folders/files. Maybe i didn't run gradlew build correctly, how do I run it?

**Comment by denispionicul** [comment]
couldn't you give us an alternative way of directly downloading the jar file?

**Comment by minhtet-htoon** [comment]
Yes... Maybe. I have to ask the artist I worked with for textures every time I want to do a public release under our contract terms but I haven't had contact with them in a few months. Though, there is a old release in "releases".

**Comment by denispionicul** [comment]
Ah I see, thank you

**Comment by denispionicul** [comment]
So you need permission to release the latest version into "releases"?

**Comment by gaesyeah** [comment]
Hi @Tharthar2, i have a question because im curious, what is "missing" to the port become "complete"? (i mean...some bug or weapon missing?)

PS: Sorry, my english isnt good

**Comment by denispionicul** [comment]
> Hi @Tharthar2, i have a question because im curious, what is "missing" to the port become "complete"? (i mean...some bug or weapon missing?)
> 
> PS: Sorry, my english isnt good

I'm assuming it's probably myrmex weapons

**Comment by saviourom** [comment]
this is like, a month later but does anyone happen to have a solution to this?

**Comment by saviourom** [comment]
> this is like, a month later but does anyone happen to have a solution to this?

nevermind im dumb and didnt check the releases
