### ISSUE TITLE
Any Update?

### ISSUE THREAD

**Issue by lSherozl** [Tharthar2/SaF2021#3]
So it is December's end now, is there any update on how this mod is coming along, will it be ready anytime soon if not can other members of the community help or take over?

**Comment by minhtet-htoon** [comment]
The legal issues with textures still aren't resolving (https://github.com/Tharthar2/SaF2021/issues/2#issuecomment-958396170). Most of my code is done, just more copy and paste. I would refer you to https://github.com/ChaosBuffalo/SpartanFire/tree/1.16.x

**Comment by minhtet-htoon** [comment]
TL;DR, I hired an external artist for the project and their contract won't allow me to create a release without their permission but I haven't seen them in months. I would be happy if somebody took this over.

**Comment by lSherozl** [comment]
Okay thank you, but how exactly do I download what is done, and if the person who created the textures also did it for ice and fire, why don't you join the discord for ice and fire, or alex mobs, and contact the creator or mod there, and try and get in touch with the person through them. Or maybe you can contact the creators of Spartan weaponry, and see if you can work with them, since they just released beta 1.16.5, and are planning to update to 1.18

**Comment by minhtet-htoon** [comment]
I think you're misunderstanding me. The artist was a random art student I knew, not anybody significant. They went for foreign exchange. If you want to download the code, download the repository or clone it with git.

**Comment by lSherozl** [comment]
Okay I understand, and does this contract prevent you from finding another artist in the community, or did that artist do so much work that it would be a waste to start from scratch again

**Comment by minhtet-htoon** [comment]
It was just the lightning dragon steel textures and models. You can make textures if you want

**Comment by lSherozl** [comment]
Is it possible for you to get in touch with the creators of spartan weaponary? They are in the process of updating the mod to 1.16.5 and then 1.18. I believe they should have an artist who has been making their textures and may be able to help contribute to this project since it relates to their mod as well.

**Comment by minhtet-htoon** [comment]
Spartan weaponry is already in 1.16 I thought. I think just using the official port is your best bet.

**Comment by lSherozl** [comment]
It says 1.16.5 beta was released, I don't think they have fully released it yet. It can't hurt to ask the creator about this project, and if they would be willing to help add the textures. The code as you said is basically done, its only the textures, and they do have an artist.
